# Generated by Django 4.1.7 on 2023-04-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=20)),
                ('fechaNacimiento', models.CharField(max_length=30)),
                ('rfc', models.CharField(max_length=13)),
                ('correo', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=12)),
                ('rol', models.CharField(max_length=1)),
            ],
        ),
    ]
