# Generated by Django 3.2.4 on 2023-05-02 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230502_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='monto',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='pagos',
            field=models.CharField(choices=[('Semanal', 'Semanal'), ('Quicenal', 'Quincenal'), ('Mensual', 'Mensual')], default='Semanal', max_length=9),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='status',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Inactivo', max_length=9),
        ),
    ]
