# Generated by Django 4.1.7 on 2023-04-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_prestamo_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='status',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1),
        ),
    ]
