# Generated by Django 4.1.7 on 2023-04-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_prestamo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='pagos',
            field=models.CharField(choices=[('Semanal', 'Semanal'), ('Quicenal', 'Quincenal'), ('Mensual', 'Mensual')], default='Semanal', max_length=9),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='status',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Inactivo', max_length=9),
        ),
    ]
